language: python

python:
  - "3.4"
  - "3.5"

os:
  - linux
#  - osx

env:
  - __PYSISTENCY_FASTHASH__=
  - __PYSISTENCY_FASTHASH__="YES"
  - CYTHONIZE="YES"

before_script:
  - pip install codecov
  - pip install coverage
  - '[[ "${CYTHONIZE}" == "YES" ]] && pip install cython || :'
  - '[[ "${CYTHONIZE}" == "YES" ]] && python setup.py install --cythonize || python setup.py install'
  - python -c 'import pysistency.meta; print(pysistency.meta.__file__)'
  - export COVERAGE_PROCESS_START=$(pwd)/.coveragerc

script:
  - time coverage run setup.py test

after_success:
  - coverage report
  - codecov

matrix:
  fast_finish: true
  allow_failures:
  - env: CYTHONIZE="YES"
