language: python

python:
  - "3.4"
  - "3.5"

os:
  - linux
#  - osx

env:
  - __PYSISTENCY_FASTHASH__=
  - __PYSISTENCY_FASTHASH__="YES"
  - CYTHONIZE="--cythonize"

before_script:
  - pip install codecov
  - pip install coverage
  - '[[ "${CYTHONIZE}" == "--cythonize" ]] && pip install cython'
  - export COVERAGE_PROCESS_START=$(pwd)/.coveragerc

script:
  - coverage run setup.py ${CYTHONIZE} test

after_success:
  - coverage report
  - codecov

matrix:
  fast_finish: true
  allow_failures:
  - env: CYTHONIZE='--cythonize'
